### ISSUE TITLE
Pass graphical glitch

### ISSUE THREAD

**Issue by GraphiteGraphic** [mdoleh/MoodMonsters#4]
On scene reset during the parent questions the acronym will disappear except the current letter it is referring to

**Comment by mdoleh** [comment]
This only happens on the 2nd "S" in the acronym.

Edit: It varies between scenes. Scared has it happen on 1st and 2nd "S". Sad has it happen only on the 2nd "S".

**Comment by mdoleh** [comment]
Confirmed. This is fixed.
