### ISSUE TITLE
Has the lily model always had that hole in her head?

### ISSUE THREAD

**Issue by GraphiteGraphic** [mdoleh/MoodMonsters#5]
It's visible on close up of her face. Should I worry about fixing that?

**Comment by mdoleh** [comment]
Screenshots would be helpful. Does it seem like the camera is too close to her face? Like you can see through her face rather than at it?

**Comment by GraphiteGraphic** [comment]
the camera is fine, the model itself has a hole in the forehead that the hair should be covering

**Comment by mdoleh** [comment]
It appears to be exposed by the face animation I used to get her to look angry. It doesn't appear at any other point in the scene. I'll let Matt know so he can keep an eye out for it while he fixes the animation.

**Comment by mdoleh** [comment]
Created a new character model with a default angry face. Matt is working on animating the face only to have the different emotions we need. Also need to figure out why the new model isn't changing animation states properly.

**Comment by mdoleh** [comment]
I believe Matt has a solution figured out. Now just waiting on him to implement the animations.

**Comment by mdoleh** [comment]
The hole only appeared when transitioning from "content" to "angry" so I just recreated her model to be permanently angry in Fuse and left her face that way through the entire scene.
