### ISSUE TITLE
Scene 3 Camera

### ISSUE THREAD

**Issue by GraphiteGraphic** [mdoleh/MoodMonsters#7]
It points away from the scene during the body language questions

**Comment by mdoleh** [comment]
I think this was due to you having a bad build. I can't reproduce this.

**Comment by mdoleh** [comment]
I got it to happen in the Scared Scene. It points the camera where the Sad Scene takes place. In order to get it to happen, you'd have to play a previous scene first then play another scene after it.

**Comment by mdoleh** [comment]
Confirmed. This issue is fixed.
