### ISSUE TITLE
Adult Gender Question

### ISSUE THREAD

**Issue by GraphiteGraphic** [mdoleh/MoodMonsters#9]
Is there a purpose to this question in the game? there seemingly has no effect on the scenes or the game in general.

**Comment by mdoleh** [comment]
It should change the gender of the parent in the scene. It that not happening?

**Comment by GraphiteGraphic** [comment]
nope, only the woman appears in the scenes

**Comment by mdoleh** [comment]
Confirmed. This is fixed.
